// Code generated by "stringer -output stringers.go -type HandleType"; DO NOT EDIT.

package assert

import "fmt"

const _HandleType_name = "ErrorHandleFatalHandle"

var _HandleType_index = [...]uint8{0, 11, 22}

func (i HandleType) String() string {
	if i < 0 || i >= HandleType(len(_HandleType_index)-1) {
		return fmt.Sprintf("HandleType(%d)", i)
	}
	return _HandleType_name[_HandleType_index[i]:_HandleType_index[i+1]]
}
